runtime: fix for glibc 2.30
glibc 2.30 moved definition of getdents64 to dirent_ext.h. Hence, it
became visible to us (via dirent.h) and conflicts with our definition:
  runtime/POSIX/fd_64.c:112:5: error: conflicting types for 'getdents64'
  int getdents64(unsigned int fd, struct dirent *dirp, unsigned int count) {
      ^
  /usr/include/bits/dirent_ext.h:29:18: note: previous declaration is here
  extern __ssize_t getdents64 (int __fd, void *__buffer, size_t __length)

We use the parameters defined by kernel, not by userspace (libc). Both
glibc and uclibc define it as:
  ssize_t __getdents64 (int fd, char *buf, size_t nbytes)
so follow it.